name             'chef-ohai-hints'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures chef-ohai-hints'
long_description 'Installs/Configures chef-ohai-hints'
version          '0.1.0'
